// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3RbfC_UygAUq9SkwYQDp21Z6YkeAMQE',
    appId: '1:99122537630:web:a53ef3be9f5e5e4ff9878f',
    messagingSenderId: '99122537630',
    projectId: 'chatapp-6c85e',
    authDomain: 'chatapp-6c85e.firebaseapp.com',
    storageBucket: 'chatapp-6c85e.appspot.com',
    measurementId: 'G-5SY33YNT90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakOeNtKdMx812lpLtJ1Y85V3cA-BpqS0',
    appId: '1:99122537630:android:a43ce69eef9592e3f9878f',
    messagingSenderId: '99122537630',
    projectId: 'chatapp-6c85e',
    storageBucket: 'chatapp-6c85e.appspot.com',
  );
}
