// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yDOHMXK177OhzDZuE-koGNBKG4ETk2o',
    appId: '1:764369040770:web:f960baf9dfb55f66880b9b',
    messagingSenderId: '764369040770',
    projectId: 'chatapp-9b53e',
    authDomain: 'chatapp-9b53e.firebaseapp.com',
    storageBucket: 'chatapp-9b53e.appspot.com',
    measurementId: 'G-LZH4V16ED0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PIEnyIkwprdiH1k-HGBwLuQIdVxZDPQ',
    appId: '1:764369040770:android:82f330f6bc4c10ee880b9b',
    messagingSenderId: '764369040770',
    projectId: 'chatapp-9b53e',
    storageBucket: 'chatapp-9b53e.appspot.com',
  );
}
